import {
  ShieldCheck, BookOpen, Scale, Heart, CheckCircle2,
  ArrowRight, Star, HelpCircle, Landmark, Users2
} from 'lucide-react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import PageHero from '../components/PageHero'
import useScrollReveal from '../hooks/useScrollReveal'
import { Link } from 'react-router-dom'
import { useState } from 'react'

const principles = [
  {
    icon: Scale,
    title: 'Prohibition of Riba (Interest)',
    arabic: 'تحريم الربا',
    hausa: 'Haramcin Riba',
    desc: 'Islamic finance strictly prohibits riba — the charging or payment of interest. All Rima MFB Shariah products are structured to generate returns through trade, profit-sharing, or service fees — never through interest.',
  },
  {
    icon: ShieldCheck,
    title: 'Halal Transactions Only',
    arabic: 'المعاملات الحلال',
    hausa: 'Mu\'amalar Halal ne',
    desc: 'We do not finance activities that are haram (forbidden) in Islam — including alcohol, gambling, tobacco, or activities that harm communities. Every product is screened for Shariah compliance.',
  },
  {
    icon: Heart,
    title: 'Asset-Backed Finance',
    arabic: 'التمويل المدعوم بالأصول',
    hausa: 'Kuɗi Mai Baya da Kayayyaki',
    desc: 'In Islamic finance, money cannot simply create more money. All financing must be backed by real assets, goods, or services — ensuring genuine economic activity and community benefit.',
  },
  {
    icon: BookOpen,
    title: 'Transparency & Fairness',
    arabic: 'الشفافية والعدالة',
    hausa: 'Bayyanawa da Adalci',
    desc: 'All profit margins, terms, and conditions are fully disclosed upfront. There are no hidden fees or surprise charges. Both parties must agree to terms — reflecting the Islamic principle of mutual consent.',
  },
]

const products = [
  {
    name: 'Qard Hasan',
    arabic: 'القرض الحسن',
    hausa: 'Lamunin Alheri',
    type: 'Benevolent Loan',
    interest: '0%',
    badge: 'Interest-Free',
    desc: 'Qard Hasan literally means "a beautiful loan" — an interest-free loan given to someone in need. The borrower repays only the principal. Rima MFB offers this as a core product for eligible customers facing financial hardship.',
    howItWorks: [
      'Customer applies with documented financial need',
      'Shariah officer reviews and approves',
      'Loan disbursed — borrower receives exact amount applied for',
      'Borrower repays only the principal over agreed schedule',
      'Zero profit, zero interest, zero hidden fees',
    ],
    verse: '"If the debtor is in difficulty, grant him time till it is easy for him to repay." — Quran 2:280',
    color: 'from-purple-600/20 to-violet-800/10',
    border: 'border-purple-500/30',
  },
  {
    name: 'Murabaha',
    arabic: 'المرابحة',
    hausa: 'Kuɗin Kasuwanci na Halal',
    type: 'Cost-Plus Trade Finance',
    interest: 'Fixed Profit Margin (Disclosed)',
    badge: 'Shariah-Compliant',
    desc: 'Murabaha is a cost-plus financing structure. Instead of lending you money (which creates riba), Rima MFB purchases the goods or asset you need and sells it to you at a disclosed profit margin. The transaction is fully transparent — you know exactly what the bank paid and what profit it is making.',
    howItWorks: [
      'Customer identifies goods/asset and submits pro-forma invoice',
      'Bank purchases the goods directly from the seller',
      'Bank sells goods to customer at cost + disclosed profit margin',
      'Customer repays in agreed instalments',
      'Profit margin is fixed upfront — cannot increase',
    ],
    verse: '"Allah has permitted trade and forbidden riba (usury)." — Quran 2:275',
    color: 'from-emerald-600/20 to-green-800/10',
    border: 'border-emerald-500/30',
  },
  {
    name: 'Non-Interest Savings',
    arabic: 'الادخار بدون فوائد',
    hausa: 'Ajiyar Ba Riba',
    type: 'Profit-Sharing Deposit',
    interest: 'Profit Share (not interest)',
    badge: 'Halal Account',
    desc: 'Our Shariah-compliant savings accounts operate on a profit-sharing (Mudarabah) basis. Instead of receiving a fixed interest rate, depositors share in the profits generated by the bank\'s halal investment activities.',
    howItWorks: [
      'Customer opens account and selects Shariah option',
      'Deposits pooled for halal investment activities',
      'Profits generated from real economic activity',
      'Profit shared with depositors on agreed ratio',
      'No guaranteed rate — but no riba involved',
    ],
    verse: '"O you who believe! Do not consume interest, doubled and multiplied." — Quran 3:130',
    color: 'from-teal-600/20 to-emerald-800/10',
    border: 'border-teal-500/30',
  },
]

const board = [
  { name: 'Sheikh Malam Umar Al-Farouq',    role: 'Chairman, Shariah Supervisory Board', qualification: 'PhD Islamic Finance, University of Medina' },
  { name: 'Dr. Abubakar Siddiq Aliyu',       role: 'Shariah Board Member',                 qualification: 'MA Fiqh Muamalat, Ahmadu Bello University' },
  { name: 'Malam Yusuf Dan-Musa',            role: 'Internal Shariah Officer',              qualification: 'Certified Islamic Finance Practitioner (CIFP)' },
]

const faqs = [
  { q: 'Is Rima MFB\'s Islamic banking truly halal?', a: 'Yes. All Shariah products are reviewed and approved by our independent Shariah Supervisory Board, composed of qualified Islamic scholars. No product is marketed as Shariah-compliant without their written fatwa (ruling).' },
  { q: 'Can non-Muslims use the Shariah products?', a: 'Absolutely. Shariah-compliant products are available to all customers regardless of religion. Many non-Muslim customers prefer them for their transparency and ethical structure.' },
  { q: 'How is Murabaha different from a normal loan?', a: 'In a normal loan, the bank lends you money and charges interest. In Murabaha, the bank buys the goods and sells them to you at a disclosed profit. The key difference: no riba. The profit margin is agreed upfront and cannot change.' },
  { q: 'What is the profit rate on Murabaha?', a: 'The profit margin is disclosed upfront and agreed before the contract is signed. It cannot increase during the financing period. Unlike interest, it is fixed and known from day one.' },
  { q: 'Can I switch my existing account to Shariah-compliant?', a: 'Yes. Visit any branch and request a Shariah account conversion. Our team will guide you through the process, which typically takes 24–48 hours.' },
]

function RevealCard({ children, delay = 0 }) {
  const { ref, visible } = useScrollReveal()
  return (
    <div ref={ref} className={`transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}
      style={{ transitionDelay: `${delay}ms` }}>
      {children}
    </div>
  )
}

export default function ShariahPage() {
  const [openFaq, setOpenFaq] = useState(null)

  return (
    <div className="min-h-screen bg-rima-dark">
      <Navbar />
      <PageHero
        title="Islamic Banking"
        hausa="Bankin Musulunci · Halal Finance"
        subtitle="The first-mover in digital Islamic banking in Northern Nigeria. Qard Hasan, Murabaha, and Shariah-compliant savings — approved by our Shariah Supervisory Board."
        breadcrumb={[{ label: 'Islamic Banking' }]}
      />

      <section className="py-20 max-w-7xl mx-auto px-6">

        {/* Hero quote */}
        <RevealCard>
          <div className="card-glass p-8 mb-16 text-center border border-rima-gold/30 relative overflow-hidden">
            <div className="absolute inset-0 pattern-overlay opacity-30 pointer-events-none" />
            <div className="relative">
              <p className="text-rima-gold/40 text-4xl mb-3 font-arabic">"</p>
              <p className="text-white text-xl font-display leading-relaxed mb-2">
                وَأَحَلَّ اللَّهُ الْبَيْعَ وَحَرَّمَ الرِّبَا
              </p>
              <p className="text-rima-gold font-semibold text-lg italic mb-2">
                "Allah has permitted trade and forbidden riba (usury)."
              </p>
              <p className="text-white/40 text-sm">— Quran 2:275</p>
            </div>
          </div>
        </RevealCard>

        {/* What is Islamic Banking */}
        <div className="grid md:grid-cols-2 gap-16 items-center mb-24">
          <RevealCard>
            <span className="text-rima-gold text-xs font-bold tracking-widest uppercase">What Is Islamic Banking?</span>
            <h2 className="font-display text-4xl font-bold text-white mt-3 mb-4">
              Banking That Aligns<br /><span className="gold-text">With Your Faith</span>
            </h2>
            <div className="w-16 h-1 bg-gold-gradient rounded-full mb-5" />
            <p className="text-white/65 leading-relaxed mb-4">
              Islamic banking operates according to Shariah (Islamic law) principles. At its core is the prohibition of
              <strong className="text-white"> riba</strong> — the charging or payment of interest. Money in Islam
              is a medium of exchange, not a commodity that can grow by itself.
            </p>
            <p className="text-white/55 leading-relaxed mb-4">
              Instead of interest, Islamic banks use structures like <strong className="text-white">Murabaha</strong> (trade finance),
              <strong className="text-white"> Qard Hasan</strong> (interest-free loans), and{' '}
              <strong className="text-white">Mudarabah</strong> (profit-sharing) to serve customers in a halal way.
            </p>
            <p className="text-white/55 leading-relaxed">
              Rima MFB is proud to be the <span className="text-rima-gold font-semibold">first-mover in digital Islamic banking</span> in
              Northern Nigeria — serving our Muslim community with products approved by qualified Shariah scholars.
            </p>
          </RevealCard>

          <RevealCard delay={200}>
            <div className="grid grid-cols-2 gap-4">
              {[
                { label: 'Shariah Products', value: '3+', sub: 'CBN & Shariah approved' },
                { label: 'First-Mover',       value: '✓',  sub: 'Digital Islamic banking NW Nigeria' },
                { label: 'Board Members',     value: '3',  sub: 'Qualified Islamic scholars' },
                { label: 'Since',             value: '1992', sub: 'Serving Muslim customers' },
              ].map(s => (
                <div key={s.label} className="card-glass p-5 text-center">
                  <p className="font-display text-3xl font-extrabold gold-text">{s.value}</p>
                  <p className="text-white text-xs font-semibold mt-1">{s.label}</p>
                  <p className="text-white/40 text-xs">{s.sub}</p>
                </div>
              ))}
            </div>
          </RevealCard>
        </div>

        {/* Core Principles */}
        <div className="mb-24">
          <div className="text-center mb-12">
            <span className="text-rima-gold text-xs font-bold tracking-widest uppercase">The Foundation</span>
            <h2 className="font-display text-4xl font-bold text-white mt-2 mb-3">Core Principles</h2>
            <div className="divider-gold" />
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {principles.map((p, i) => {
              const Icon = p.icon
              return (
                <RevealCard key={p.title} delay={i * 100}>
                  <div className="card-glass p-6 h-full">
                    <div className="w-12 h-12 rounded-xl bg-rima-gold/10 border border-rima-gold/20 flex items-center justify-center mb-4">
                      <Icon size={22} className="text-rima-gold" />
                    </div>
                    <p className="text-rima-gold/40 text-xs mb-0.5 font-arabic">{p.arabic}</p>
                    <p className="text-rima-gold/50 text-xs italic mb-2">{p.hausa}</p>
                    <h3 className="font-display font-bold text-white text-base mb-2">{p.title}</h3>
                    <p className="text-white/55 text-sm leading-relaxed">{p.desc}</p>
                  </div>
                </RevealCard>
              )
            })}
          </div>
        </div>

        {/* Products */}
        <div className="mb-24">
          <div className="text-center mb-12">
            <span className="text-rima-gold text-xs font-bold tracking-widest uppercase">Shariah-Compliant Products</span>
            <h2 className="font-display text-4xl font-bold text-white mt-2 mb-3">Our Halal Products</h2>
            <div className="divider-gold" />
          </div>
          <div className="flex flex-col gap-6">
            {products.map((product, i) => (
              <RevealCard key={product.name} delay={i * 100}>
                <div className={`card-glass p-8 bg-gradient-to-b ${product.color} border ${product.border}`}>
                  <div className="grid md:grid-cols-2 gap-8">
                    <div>
                      <div className="flex items-start gap-4 mb-4">
                        <div>
                          <p className="text-rima-gold/50 text-sm font-arabic mb-0.5">{product.arabic}</p>
                          <h3 className="font-display font-extrabold text-white text-2xl">{product.name}</h3>
                          <p className="text-rima-gold/60 text-xs italic mb-1">{product.hausa}</p>
                          <div className="flex gap-2 flex-wrap mt-2">
                            <span className="text-xs bg-rima-gold/10 border border-rima-gold/20 text-rima-gold px-2.5 py-0.5 rounded-full font-semibold">
                              {product.type}
                            </span>
                            <span className="text-xs bg-green-500/10 border border-green-500/20 text-green-400 px-2.5 py-0.5 rounded-full font-semibold">
                              {product.badge}
                            </span>
                          </div>
                        </div>
                      </div>
                      <p className="text-white/65 text-sm leading-relaxed mb-4">{product.desc}</p>
                      <blockquote className="border-l-2 border-rima-gold/40 pl-4 text-rima-gold/60 text-xs italic">
                        {product.verse}
                      </blockquote>
                    </div>
                    <div>
                      <p className="text-rima-gold text-xs font-bold uppercase tracking-wider mb-3 flex items-center gap-2">
                        <CheckCircle2 size={13} /> How It Works
                      </p>
                      <ol className="space-y-3">
                        {product.howItWorks.map((step, j) => (
                          <li key={j} className="flex items-start gap-3 text-white/60 text-sm">
                            <span className="w-5 h-5 rounded-full bg-rima-gold/20 border border-rima-gold/30 text-rima-gold text-xs
                                             flex items-center justify-center flex-shrink-0 mt-0.5 font-bold">{j + 1}</span>
                            {step}
                          </li>
                        ))}
                      </ol>
                      <Link to={product.name === 'Qard Hasan' || product.name === 'Murabaha' ? '/loans/apply' : '/open-account'}
                        className="btn-gold text-sm flex items-center gap-2 mt-6 w-fit">
                        Apply Now <ArrowRight size={14} />
                      </Link>
                    </div>
                  </div>
                </div>
              </RevealCard>
            ))}
          </div>
        </div>

        {/* Shariah Board */}
        <div className="mb-24">
          <div className="text-center mb-12">
            <span className="text-rima-gold text-xs font-bold tracking-widest uppercase">Oversight & Governance</span>
            <h2 className="font-display text-4xl font-bold text-white mt-2 mb-3">Shariah Supervisory Board</h2>
            <div className="divider-gold" />
            <p className="text-white/55 max-w-xl mx-auto mt-4 text-sm">
              Every Shariah product at Rima MFB is reviewed, approved, and continuously monitored by our independent
              Shariah Supervisory Board — composed of qualified Islamic scholars.
            </p>
          </div>
          <div className="grid sm:grid-cols-3 gap-5">
            {board.map((m, i) => (
              <RevealCard key={m.name} delay={i * 100}>
                <div className="card-glass p-6 text-center">
                  <div className="w-16 h-16 rounded-full bg-rima-gold/15 border-2 border-rima-gold/30
                                   flex items-center justify-center mx-auto mb-4">
                    <Landmark size={28} className="text-rima-gold" />
                  </div>
                  <h3 className="font-display font-bold text-white text-base">{m.name}</h3>
                  <p className="text-rima-gold/70 text-xs mt-1">{m.role}</p>
                  <p className="text-white/40 text-xs mt-1">{m.qualification}</p>
                  <div className="flex justify-center gap-1 mt-3">
                    {[...Array(5)].map((_, j) => (
                      <Star key={j} size={10} className="text-rima-gold fill-rima-gold" />
                    ))}
                  </div>
                </div>
              </RevealCard>
            ))}
          </div>
        </div>

        {/* FAQ */}
        <div className="mb-16">
          <div className="text-center mb-10">
            <h2 className="font-display text-3xl font-bold text-white">Common Questions</h2>
            <div className="divider-gold" />
          </div>
          <div className="max-w-3xl mx-auto flex flex-col gap-3">
            {faqs.map((faq, i) => (
              <RevealCard key={i} delay={i * 60}>
                <div className="card-glass overflow-hidden">
                  <button onClick={() => setOpenFaq(openFaq === i ? null : i)}
                    className="w-full px-6 py-4 flex items-start gap-3 text-left">
                    <HelpCircle size={16} className="text-rima-gold flex-shrink-0 mt-0.5" />
                    <p className="text-white font-semibold text-sm flex-1">{faq.q}</p>
                    <span className="text-rima-gold/60 text-lg">{openFaq === i ? '−' : '+'}</span>
                  </button>
                  <div className={`overflow-hidden transition-all duration-300 ${openFaq === i ? 'max-h-40 opacity-100' : 'max-h-0 opacity-0'}`}>
                    <p className="px-6 pb-5 text-white/60 text-sm leading-relaxed">{faq.a}</p>
                  </div>
                </div>
              </RevealCard>
            ))}
          </div>
        </div>

        {/* CTA */}
        <RevealCard>
          <div className="card-glass p-10 text-center relative overflow-hidden border border-rima-gold/30">
            <div className="absolute inset-0 pattern-overlay opacity-30 pointer-events-none" />
            <div className="relative">
              <div className="w-16 h-16 rounded-full bg-rima-gold/15 border-2 border-rima-gold/30 flex items-center justify-center mx-auto mb-5">
                <Landmark size={30} className="text-rima-gold" />
              </div>
              <h3 className="font-display text-3xl font-bold text-white mb-2">
                Bank With Confidence
              </h3>
              <p className="text-rima-gold italic text-lg mb-2">Halal. Transparent. Trusted.</p>
              <p className="text-white/50 mb-6 max-w-md mx-auto text-sm">
                Apply for a Qard Hasan loan, Murabaha finance, or open a Shariah-compliant savings account today.
              </p>
              <div className="flex justify-center flex-wrap gap-4">
                <Link to="/loans/apply" className="btn-gold flex items-center gap-2">
                  Apply for Halal Loan <ArrowRight size={16} />
                </Link>
                <Link to="/open-account" className="btn-outline-gold">
                  Open Shariah Account
                </Link>
              </div>
            </div>
          </div>
        </RevealCard>
      </section>
      <Footer />
    </div>
  )
}
